name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Build the Docker image
      run: docker build -t ombrelin/rc-backend:lastest . --file Dockerfile
    - name: Docker login
      run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login --username ombrelin --password-stdin
    - name: Publish to Docker hub
      run: docker push ombrelin/rc-backend:latest